import { ProductAttribute, AttributeType } from '@/types/product';

// Define CategoryConfig interface
export interface CategoryConfig {
  id: string;
  name: string;
  description: string;
  icon: string;
  attributes: ProductAttribute[];
  requiredFields: string[];
  recommendedFields: string[];
  customFields: string[];
}

// Category-specific attribute configurations
export const CATEGORY_ATTRIBUTES: Record<string, ProductAttribute[]> = {
  // Shoes Category
  'Women\'s Shoes': [
    {
      id: 'color',
      name: 'Color',
      slug: 'color',
      type: 'color' as AttributeType,
      values: [
        { id: 'black', name: 'Black', color: '#000000' },
        { id: 'white', name: 'White', color: '#FFFFFF' },
        { id: 'red', name: 'Red', color: '#EF4444' },
        { id: 'blue', name: 'Blue', color: '#3B82F6' },
        { id: 'brown', name: 'Brown', color: '#92400E' },
        { id: 'beige', name: 'Beige', color: '#D4B08A' },
        { id: 'pink', name: 'Pink', color: '#EC4899' },
        { id: 'purple', name: 'Purple', color: '#8B5CF6' },
        { id: 'green', name: 'Green', color: '#10B981' },
        { id: 'yellow', name: 'Yellow', color: '#F59E0B' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'size',
      name: 'Size (US)',
      slug: 'size',
      type: 'select' as AttributeType,
      values: [
        { id: '5', name: '5' },
        { id: '5.5', name: '5.5' },
        { id: '6', name: '6' },
        { id: '6.5', name: '6.5' },
        { id: '7', name: '7' },
        { id: '7.5', name: '7.5' },
        { id: '8', name: '8' },
        { id: '8.5', name: '8.5' },
        { id: '9', name: '9' },
        { id: '9.5', name: '9.5' },
        { id: '10', name: '10' },
        { id: '10.5', name: '10.5' },
        { id: '11', name: '11' },
        { id: '11.5', name: '11.5' },
        { id: '12', name: '12' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'material',
      name: 'Material',
      slug: 'material',
      type: 'select' as AttributeType,
      values: [
        { id: 'genuine_leather', name: 'Genuine Leather' },
        { id: 'synthetic_leather', name: 'Synthetic Leather' },
        { id: 'canvas', name: 'Canvas' },
        { id: 'suede', name: 'Suede' },
        { id: 'mesh', name: 'Mesh' },
        { id: 'rubber', name: 'Rubber' },
        { id: 'fabric', name: 'Fabric' },
        { id: 'velvet', name: 'Velvet' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'style',
      name: 'Style',
      slug: 'style',
      type: 'select' as AttributeType,
      values: [
        { id: 'sneakers', name: 'Sneakers' },
        { id: 'running_shoes', name: 'Running Shoes' },
        { id: 'boots', name: 'Boots' },
        { id: 'sandals', name: 'Sandals' },
        { id: 'heels', name: 'Heels' },
        { id: 'flats', name: 'Flats' },
        { id: 'loafers', name: 'Loafers' },
        { id: 'oxfords', name: 'Oxfords' },
        { id: 'espadrilles', name: 'Espadrilles' },
        { id: 'mules', name: 'Mules' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'heel_height',
      name: 'Heel Height',
      slug: 'heel_height',
      type: 'select' as AttributeType,
      values: [
        { id: 'flat', name: 'Flat (0-1 inch)' },
        { id: 'low', name: 'Low (1-2 inches)' },
        { id: 'mid', name: 'Mid (2-3 inches)' },
        { id: 'high', name: 'High (3-4 inches)' },
        { id: 'ultra_high', name: 'Ultra High (4+ inches)' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'closure_type',
      name: 'Closure Type',
      slug: 'closure_type',
      type: 'select' as AttributeType,
      values: [
        { id: 'lace_up', name: 'Lace Up' },
        { id: 'slip_on', name: 'Slip On' },
        { id: 'buckle', name: 'Buckle' },
        { id: 'zipper', name: 'Zipper' },
        { id: 'velcro', name: 'Velcro' },
        { id: 'elastic', name: 'Elastic' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
  ],

  'Men\'s Shoes': [
    {
      id: 'color',
      name: 'Color',
      slug: 'color',
      type: 'color' as AttributeType,
      values: [
        { id: 'black', name: 'Black', color: '#000000' },
        { id: 'white', name: 'White', color: '#FFFFFF' },
        { id: 'brown', name: 'Brown', color: '#92400E' },
        { id: 'navy', name: 'Navy', color: '#1E40AF' },
        { id: 'gray', name: 'Gray', color: '#6B7280' },
        { id: 'tan', name: 'Tan', color: '#D97706' },
        { id: 'red', name: 'Red', color: '#EF4444' },
        { id: 'blue', name: 'Blue', color: '#3B82F6' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'size',
      name: 'Size (US)',
      slug: 'size',
      type: 'select' as AttributeType,
      values: [
        { id: '7', name: '7' },
        { id: '7.5', name: '7.5' },
        { id: '8', name: '8' },
        { id: '8.5', name: '8.5' },
        { id: '9', name: '9' },
        { id: '9.5', name: '9.5' },
        { id: '10', name: '10' },
        { id: '10.5', name: '10.5' },
        { id: '11', name: '11' },
        { id: '11.5', name: '11.5' },
        { id: '12', name: '12' },
        { id: '12.5', name: '12.5' },
        { id: '13', name: '13' },
        { id: '14', name: '14' },
        { id: '15', name: '15' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'material',
      name: 'Material',
      slug: 'material',
      type: 'select' as AttributeType,
      values: [
        { id: 'genuine_leather', name: 'Genuine Leather' },
        { id: 'synthetic_leather', name: 'Synthetic Leather' },
        { id: 'canvas', name: 'Canvas' },
        { id: 'suede', name: 'Suede' },
        { id: 'mesh', name: 'Mesh' },
        { id: 'rubber', name: 'Rubber' },
        { id: 'fabric', name: 'Fabric' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'style',
      name: 'Style',
      slug: 'style',
      type: 'select' as AttributeType,
      values: [
        { id: 'sneakers', name: 'Sneakers' },
        { id: 'running_shoes', name: 'Running Shoes' },
        { id: 'boots', name: 'Boots' },
        { id: 'sandals', name: 'Sandals' },
        { id: 'oxfords', name: 'Oxfords' },
        { id: 'loafers', name: 'Loafers' },
        { id: 'derby', name: 'Derby' },
        { id: 'monk_strap', name: 'Monk Strap' },
        { id: 'slippers', name: 'Slippers' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'closure_type',
      name: 'Closure Type',
      slug: 'closure_type',
      type: 'select' as AttributeType,
      values: [
        { id: 'lace_up', name: 'Lace Up' },
        { id: 'slip_on', name: 'Slip On' },
        { id: 'buckle', name: 'Buckle' },
        { id: 'zipper', name: 'Zipper' },
        { id: 'velcro', name: 'Velcro' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
  ],

  // Dresses Category
  'Dresses': [
    {
      id: 'color',
      name: 'Color',
      slug: 'color',
      type: 'color' as AttributeType,
      values: [
        { id: 'black', name: 'Black', color: '#000000' },
        { id: 'white', name: 'White', color: '#FFFFFF' },
        { id: 'red', name: 'Red', color: '#EF4444' },
        { id: 'blue', name: 'Blue', color: '#3B82F6' },
        { id: 'pink', name: 'Pink', color: '#EC4899' },
        { id: 'purple', name: 'Purple', color: '#8B5CF6' },
        { id: 'green', name: 'Green', color: '#10B981' },
        { id: 'yellow', name: 'Yellow', color: '#F59E0B' },
        { id: 'navy', name: 'Navy', color: '#1E40AF' },
        { id: 'gray', name: 'Gray', color: '#6B7280' },
        { id: 'beige', name: 'Beige', color: '#D4B08A' },
        { id: 'coral', name: 'Coral', color: '#FF7F50' },
        { id: 'mint', name: 'Mint', color: '#98FF98' },
        { id: 'lavender', name: 'Lavender', color: '#E6E6FA' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'size',
      name: 'Size',
      slug: 'size',
      type: 'select' as AttributeType,
      values: [
        { id: 'xs', name: 'XS' },
        { id: 's', name: 'S' },
        { id: 'm', name: 'M' },
        { id: 'l', name: 'L' },
        { id: 'xl', name: 'XL' },
        { id: 'xxl', name: 'XXL' },
        { id: 'xxxl', name: 'XXXL' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'material',
      name: 'Material',
      slug: 'material',
      type: 'select' as AttributeType,
      values: [
        { id: 'cotton', name: 'Cotton' },
        { id: 'silk', name: 'Silk' },
        { id: 'chiffon', name: 'Chiffon' },
        { id: 'lace', name: 'Lace' },
        { id: 'satin', name: 'Satin' },
        { id: 'velvet', name: 'Velvet' },
        { id: 'jersey', name: 'Jersey' },
        { id: 'linen', name: 'Linen' },
        { id: 'polyester', name: 'Polyester' },
        { id: 'rayon', name: 'Rayon' },
        { id: 'wool', name: 'Wool' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'style',
      name: 'Style',
      slug: 'style',
      type: 'select' as AttributeType,
      values: [
        { id: 'maxi', name: 'Maxi Dress' },
        { id: 'midi', name: 'Midi Dress' },
        { id: 'mini', name: 'Mini Dress' },
        { id: 'bodycon', name: 'Bodycon' },
        { id: 'shift', name: 'Shift Dress' },
        { id: 'wrap', name: 'Wrap Dress' },
        { id: 'sheath', name: 'Sheath Dress' },
        { id: 'a_line', name: 'A-Line' },
        { id: 'fit_and_flare', name: 'Fit & Flare' },
        { id: 'empire', name: 'Empire Waist' },
        { id: 'off_shoulder', name: 'Off-Shoulder' },
        { id: 'halter', name: 'Halter Neck' },
        { id: 'strapless', name: 'Strapless' },
        { id: 'one_shoulder', name: 'One Shoulder' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'neckline',
      name: 'Neckline',
      slug: 'neckline',
      type: 'select' as AttributeType,
      values: [
        { id: 'v_neck', name: 'V-Neck' },
        { id: 'round_neck', name: 'Round Neck' },
        { id: 'square_neck', name: 'Square Neck' },
        { id: 'scoop_neck', name: 'Scoop Neck' },
        { id: 'boat_neck', name: 'Boat Neck' },
        { id: 'sweetheart', name: 'Sweetheart' },
        { id: 'halter', name: 'Halter' },
        { id: 'off_shoulder', name: 'Off-Shoulder' },
        { id: 'one_shoulder', name: 'One Shoulder' },
        { id: 'turtleneck', name: 'Turtleneck' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'sleeve_length',
      name: 'Sleeve Length',
      slug: 'sleeve_length',
      type: 'select' as AttributeType,
      values: [
        { id: 'sleeveless', name: 'Sleeveless' },
        { id: 'short', name: 'Short Sleeve' },
        { id: '3_4', name: '3/4 Sleeve' },
        { id: 'long', name: 'Long Sleeve' },
        { id: 'bell', name: 'Bell Sleeve' },
        { id: 'puff', name: 'Puff Sleeve' },
        { id: 'bishop', name: 'Bishop Sleeve' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'pattern',
      name: 'Pattern',
      slug: 'pattern',
      type: 'select' as AttributeType,
      values: [
        { id: 'solid', name: 'Solid' },
        { id: 'floral', name: 'Floral' },
        { id: 'striped', name: 'Striped' },
        { id: 'polka_dot', name: 'Polka Dot' },
        { id: 'animal_print', name: 'Animal Print' },
        { id: 'geometric', name: 'Geometric' },
        { id: 'abstract', name: 'Abstract' },
        { id: 'plaid', name: 'Plaid' },
        { id: 'lace', name: 'Lace' },
        { id: 'embroidered', name: 'Embroidered' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
  ],

  // T-Shirts Category
  'T-Shirts': [
    {
      id: 'color',
      name: 'Color',
      slug: 'color',
      type: 'color' as AttributeType,
      values: [
        { id: 'white', name: 'White', color: '#FFFFFF' },
        { id: 'black', name: 'Black', color: '#000000' },
        { id: 'gray', name: 'Gray', color: '#6B7280' },
        { id: 'navy', name: 'Navy', color: '#1E40AF' },
        { id: 'red', name: 'Red', color: '#EF4444' },
        { id: 'blue', name: 'Blue', color: '#3B82F6' },
        { id: 'green', name: 'Green', color: '#10B981' },
        { id: 'yellow', name: 'Yellow', color: '#F59E0B' },
        { id: 'pink', name: 'Pink', color: '#EC4899' },
        { id: 'purple', name: 'Purple', color: '#8B5CF6' },
        { id: 'orange', name: 'Orange', color: '#F97316' },
        { id: 'brown', name: 'Brown', color: '#92400E' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'size',
      name: 'Size',
      slug: 'size',
      type: 'select' as AttributeType,
      values: [
        { id: 'xs', name: 'XS' },
        { id: 's', name: 'S' },
        { id: 'm', name: 'M' },
        { id: 'l', name: 'L' },
        { id: 'xl', name: 'XL' },
        { id: 'xxl', name: 'XXL' },
        { id: 'xxxl', name: 'XXXL' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'material',
      name: 'Material',
      slug: 'material',
      type: 'select' as AttributeType,
      values: [
        { id: 'cotton', name: '100% Cotton' },
        { id: 'organic_cotton', name: 'Organic Cotton' },
        { id: 'pima_cotton', name: 'Pima Cotton' },
        { id: 'cotton_blend', name: 'Cotton Blend' },
        { id: 'polyester', name: 'Polyester' },
        { id: 'bamboo', name: 'Bamboo' },
        { id: 'modal', name: 'Modal' },
        { id: 'hemp', name: 'Hemp' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'fit',
      name: 'Fit',
      slug: 'fit',
      type: 'select' as AttributeType,
      values: [
        { id: 'regular', name: 'Regular Fit' },
        { id: 'slim', name: 'Slim Fit' },
        { id: 'loose', name: 'Loose Fit' },
        { id: 'oversized', name: 'Oversized' },
        { id: 'athletic', name: 'Athletic Fit' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'sleeve_length',
      name: 'Sleeve Length',
      slug: 'sleeve_length',
      type: 'select' as AttributeType,
      values: [
        { id: 'short', name: 'Short Sleeve' },
        { id: 'long', name: 'Long Sleeve' },
        { id: 'sleeveless', name: 'Sleeveless' },
        { id: '3_4', name: '3/4 Sleeve' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'neckline',
      name: 'Neckline',
      slug: 'neckline',
      type: 'select' as AttributeType,
      values: [
        { id: 'crew_neck', name: 'Crew Neck' },
        { id: 'v_neck', name: 'V-Neck' },
        { id: 'scoop_neck', name: 'Scoop Neck' },
        { id: 'henley', name: 'Henley' },
        { id: 'polo', name: 'Polo' },
        { id: 'turtleneck', name: 'Turtleneck' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
  ],

  // Jeans Category
  'Jeans': [
    {
      id: 'color',
      name: 'Color',
      slug: 'color',
      type: 'color' as AttributeType,
      values: [
        { id: 'blue', name: 'Blue', color: '#3B82F6' },
        { id: 'black', name: 'Black', color: '#000000' },
        { id: 'gray', name: 'Gray', color: '#6B7280' },
        { id: 'white', name: 'White', color: '#FFFFFF' },
        { id: 'dark_blue', name: 'Dark Blue', color: '#1E40AF' },
        { id: 'light_blue', name: 'Light Blue', color: '#93C5FD' },
        { id: 'indigo', name: 'Indigo', color: '#4F46E5' },
        { id: 'raw_denim', name: 'Raw Denim', color: '#64748B' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'size',
      name: 'Size',
      slug: 'size',
      type: 'select' as AttributeType,
      values: [
        { id: '24', name: '24' },
        { id: '25', name: '25' },
        { id: '26', name: '26' },
        { id: '27', name: '27' },
        { id: '28', name: '28' },
        { id: '29', name: '29' },
        { id: '30', name: '30' },
        { id: '31', name: '31' },
        { id: '32', name: '32' },
        { id: '33', name: '33' },
        { id: '34', name: '34' },
        { id: '35', name: '35' },
        { id: '36', name: '36' },
        { id: '38', name: '38' },
        { id: '40', name: '40' },
      ],
      required: true,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'fit',
      name: 'Fit',
      slug: 'fit',
      type: 'select' as AttributeType,
      values: [
        { id: 'skinny', name: 'Skinny' },
        { id: 'slim', name: 'Slim' },
        { id: 'straight', name: 'Straight' },
        { id: 'bootcut', name: 'Bootcut' },
        { id: 'flare', name: 'Flare' },
        { id: 'wide_leg', name: 'Wide Leg' },
        { id: 'relaxed', name: 'Relaxed' },
        { id: 'loose', name: 'Loose' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'rise',
      name: 'Rise',
      slug: 'rise',
      type: 'select' as AttributeType,
      values: [
        { id: 'ultra_low', name: 'Ultra Low Rise' },
        { id: 'low', name: 'Low Rise' },
        { id: 'mid', name: 'Mid Rise' },
        { id: 'high', name: 'High Rise' },
        { id: 'ultra_high', name: 'Ultra High Rise' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'material',
      name: 'Material',
      slug: 'material',
      type: 'select' as AttributeType,
      values: [
        { id: 'denim', name: 'Denim' },
        { id: 'stretch_denim', name: 'Stretch Denim' },
        { id: 'organic_denim', name: 'Organic Denim' },
        { id: 'raw_denim', name: 'Raw Denim' },
        { id: 'selvedge_denim', name: 'Selvedge Denim' },
        { id: 'cotton_blend', name: 'Cotton Blend' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
    {
      id: 'wash',
      name: 'Wash',
      slug: 'wash',
      type: 'select' as AttributeType,
      values: [
        { id: 'raw', name: 'Raw' },
        { id: 'dark', name: 'Dark Wash' },
        { id: 'medium', name: 'Medium Wash' },
        { id: 'light', name: 'Light Wash' },
        { id: 'distressed', name: 'Distressed' },
        { id: 'acid_wash', name: 'Acid Wash' },
        { id: 'stone_wash', name: 'Stone Wash' },
        { id: 'black', name: 'Black' },
        { id: 'white', name: 'White' },
      ],
      required: false,
      visible: true,
      variation: true,
      filterable: true,
      sortable: true,
      searchable: true,
    },
  ],
};

// Category configurations with additional metadata
export const CATEGORY_CONFIGS: Record<string, CategoryConfig> = {
  'Women\'s Shoes': {
    id: 'womens_shoes',
    name: 'Women\'s Shoes',
    description: 'All types of women\'s footwear',
    icon: '👠',
    attributes: CATEGORY_ATTRIBUTES['Women\'s Shoes'],
    requiredFields: ['color', 'size'],
    recommendedFields: ['material', 'style'],
    customFields: [],
  },
  'Men\'s Shoes': {
    id: 'mens_shoes',
    name: 'Men\'s Shoes',
    description: 'All types of men\'s footwear',
    icon: '👞',
    attributes: CATEGORY_ATTRIBUTES['Men\'s Shoes'],
    requiredFields: ['color', 'size'],
    recommendedFields: ['material', 'style'],
    customFields: [],
  },
  'Dresses': {
    id: 'dresses',
    name: 'Dresses',
    description: 'Women\'s dresses for all occasions',
    icon: '👗',
    attributes: CATEGORY_ATTRIBUTES['Dresses'],
    requiredFields: ['color', 'size'],
    recommendedFields: ['material', 'style', 'neckline'],
    customFields: [],
  },
  'T-Shirts': {
    id: 't_shirts',
    name: 'T-Shirts',
    description: 'Casual and fashion t-shirts',
    icon: '👕',
    attributes: CATEGORY_ATTRIBUTES['T-Shirts'],
    requiredFields: ['color', 'size'],
    recommendedFields: ['material', 'fit'],
    customFields: [],
  },
  'Jeans': {
    id: 'jeans',
    name: 'Jeans',
    description: 'Denim jeans and pants',
    icon: '👖',
    attributes: CATEGORY_ATTRIBUTES['Jeans'],
    requiredFields: ['color', 'size'],
    recommendedFields: ['fit', 'rise', 'wash'],
    customFields: [],
  },
};

// Get all available categories
export const getAllCategories = (): string[] => {
  return Object.keys(CATEGORY_ATTRIBUTES);
};

// Get attributes for a specific category
export const getCategoryAttributes = (categoryName: string): ProductAttribute[] => {
  return CATEGORY_ATTRIBUTES[categoryName] || [];
};

// Get category config
export const getCategoryConfig = (categoryName: string): CategoryConfig | null => {
  return CATEGORY_CONFIGS[categoryName] || null;
};
