import { ProductClassification, FormField, FormSection } from '@/types/product';

// Product Classifications
export const CLASSIFICATIONS: Array<{
  id: ProductClassification;
  label: string;
  description: string;
  icon: string;
  hasInventory: boolean;
  hasShipping: boolean;
  hasVariants: boolean;
  hasFiles: boolean;
  hasSubscription: boolean;
  hasRental: boolean;
  hasEvents: boolean;
}> = [
  {
    id: 'physical',
    label: 'Physical Product',
    description: 'Tangible item shipped to customers',
    icon: '📦',
    hasInventory: true,
    hasShipping: true,
    hasVariants: true,
    hasFiles: false,
    hasSubscription: false,
    hasRental: false,
    hasEvents: false,
  },
  {
    id: 'digital',
    label: 'Digital Product',
    description: 'Downloadable files or licenses',
    icon: '💻',
    hasInventory: false,
    hasShipping: false,
    hasVariants: false,
    hasFiles: true,
    hasSubscription: false,
    hasRental: false,
    hasEvents: false,
  },
  {
    id: 'service',
    label: 'Service',
    description: 'Professional or freelance offering',
    icon: '🛠️',
    hasInventory: false,
    hasShipping: false,
    hasVariants: false,
    hasFiles: false,
    hasSubscription: false,
    hasRental: false,
    hasEvents: false,
  },
  {
    id: 'subscription',
    label: 'Subscription',
    description: 'Recurring service or product',
    icon: '🔄',
    hasInventory: false,
    hasShipping: false,
    hasVariants: false,
    hasFiles: false,
    hasSubscription: true,
    hasRental: false,
    hasEvents: false,
  },
  {
    id: 'rental',
    label: 'Rental',
    description: 'Items rented for a period (e.g., cars, apartments)',
    icon: '🚗',
    hasInventory: true,
    hasShipping: false,
    hasVariants: true,
    hasFiles: false,
    hasSubscription: false,
    hasRental: true,
    hasEvents: false,
  },
  {
    id: 'event',
    label: 'Event Ticket',
    description: 'Tickets for events or experiences',
    icon: '🎫',
    hasInventory: true,
    hasShipping: false,
    hasVariants: false,
    hasFiles: false,
    hasSubscription: false,
    hasRental: false,
    hasEvents: true,
  },
  {
    id: 'bundle',
    label: 'Bundle',
    description: 'Collection of related products',
    icon: '📦',
    hasInventory: true,
    hasShipping: true,
    hasVariants: false,
    hasFiles: false,
    hasSubscription: false,
    hasRental: false,
    hasEvents: false,
  },
];

// Industry Tree
export const INDUSTRY_TREE: Record<string, string[]> = {
  Fashion: ['Men\'s Clothing', 'Women\'s Shoes', 'Accessories', 'Bags', 'Jewelry'],
  Electronics: ['Phones', 'Laptops', 'Tablets', 'Smart Home', 'Gaming', 'Audio'],
  'Home & Garden': ['Furniture', 'Decor', 'Kitchen', 'Bathroom', 'Garden'],
  'Sports & Outdoors': ['Fitness', 'Camping', 'Cycling', 'Water Sports', 'Team Sports'],
  'Books & Media': ['Books', 'Movies', 'Music', 'Games', 'Educational'],
  'Health & Beauty': ['Skincare', 'Hair Care', 'Makeup', 'Supplements', 'Wellness'],
  'Food & Beverage': ['Snacks', 'Beverages', 'Organic', 'Gourmet', 'Dietary'],
  'Automotive': ['Parts', 'Accessories', 'Tools', 'Electronics', 'Maintenance'],
  'Services': ['Consulting', 'Design', 'Repairs', 'Cleaning', 'Tutoring'],
  'Real Estate': ['Apartments', 'Houses', 'Commercial', 'Land', 'Vacation Rentals'],
  'Software & SaaS': ['Productivity', 'Security', 'Analytics', 'Communication', 'Development'],
};

// Form Schemas for each classification
export const FORM_SCHEMAS: Record<ProductClassification, string[]> = {
  physical: ['name', 'description', 'sku', 'price', 'cost', 'stock', 'weight', 'dimensions', 'shipping_class'],
  digital: ['name', 'description', 'sku', 'price', 'cost', 'download_limit', 'download_expiry', 'files'],
  service: ['name', 'description', 'sku', 'hourly_rate', 'duration', 'availability', 'location'],
  subscription: ['name', 'description', 'sku', 'recurring_price', 'billing_cycle', 'trial_period', 'signup_fee'],
  rental: ['name', 'description', 'sku', 'daily_rate', 'deposit', 'availability_dates', 'min_rental_days'],
  event: ['name', 'description', 'sku', 'event_date', 'venue', 'capacity', 'ticket_price'],
  bundle: ['name', 'description', 'sku', 'bundled_products', 'bundle_price_type', 'bundle_discount'],
};

// Field Metadata
export const FIELD_METADATA: Record<string, FormField> = {
  // Basic Fields
  name: {
    id: 'name',
    type: 'text',
    label: 'Product Name',
    description: 'The name of your product as it will appear to customers',
    required: true,
    visible: true,
    validation: { min_length: 1, max_length: 255 },
  },
  description: {
    id: 'description',
    type: 'rich_text',
    label: 'Description',
    description: 'Detailed description of your product',
    required: false,
    visible: true,
  },
  sku: {
    id: 'sku',
    type: 'text',
    label: 'SKU',
    description: 'Stock Keeping Unit - unique identifier for inventory',
    required: false,
    visible: true,
    validation: { max_length: 100 },
  },

  // Pricing Fields
  price: {
    id: 'price',
    type: 'number',
    label: 'Price',
    description: 'Regular selling price',
    required: true,
    visible: true,
    min: 0,
    step: 0.01,
  },
  cost: {
    id: 'cost',
    type: 'number',
    label: 'Cost',
    description: 'Your cost per item (not visible to customers)',
    required: false,
    visible: true,
    min: 0,
    step: 0.01,
  },
  recurring_price: {
    id: 'recurring_price',
    type: 'number',
    label: 'Recurring Price',
    description: 'Price charged on each billing cycle',
    required: true,
    visible: true,
    min: 0,
    step: 0.01,
  },
  hourly_rate: {
    id: 'hourly_rate',
    type: 'number',
    label: 'Hourly Rate',
    description: 'Rate per hour for this service',
    required: true,
    visible: true,
    min: 0,
    step: 0.01,
  },
  daily_rate: {
    id: 'daily_rate',
    type: 'number',
    label: 'Daily Rate',
    description: 'Rate per day for rental',
    required: true,
    visible: true,
    min: 0,
    step: 0.01,
  },
  ticket_price: {
    id: 'ticket_price',
    type: 'number',
    label: 'Ticket Price',
    description: 'Price per ticket',
    required: true,
    visible: true,
    min: 0,
    step: 0.01,
  },

  // Inventory Fields
  stock: {
    id: 'stock',
    type: 'number',
    label: 'Stock Quantity',
    description: 'Number of items available',
    required: false,
    visible: true,
    min: 0,
  },

  // Shipping Fields
  weight: {
    id: 'weight',
    type: 'number',
    label: 'Weight (kg)',
    description: 'Product weight for shipping calculations',
    required: false,
    visible: true,
    min: 0,
    step: 0.01,
  },
  dimensions: {
    id: 'dimensions',
    type: 'text',
    label: 'Dimensions (L x W x H)',
    description: 'Product dimensions in cm',
    required: false,
    visible: true,
    placeholder: '30 x 20 x 10',
  },
  shipping_class: {
    id: 'shipping_class',
    type: 'select',
    label: 'Shipping Class',
    description: 'Shipping method for this product',
    required: false,
    visible: true,
    options: [
      { value: 'standard', label: 'Standard Shipping' },
      { value: 'express', label: 'Express Shipping' },
      { value: 'free', label: 'Free Shipping' },
      { value: 'local', label: 'Local Pickup Only' },
    ],
  },

  // Digital Fields
  download_limit: {
    id: 'download_limit',
    type: 'number',
    label: 'Download Limit',
    description: 'Maximum number of downloads per purchase',
    required: false,
    visible: true,
    min: 1,
  },
  download_expiry: {
    id: 'download_expiry',
    type: 'number',
    label: 'Download Expiry (Days)',
    description: 'Number of days until download expires',
    required: false,
    visible: true,
    min: 1,
  },
  files: {
    id: 'files',
    type: 'file',
    label: 'Digital Files',
    description: 'Upload files customers can download',
    required: false,
    visible: true,
  },

  // Service Fields
  duration: {
    id: 'duration',
    type: 'number',
    label: 'Duration (Hours)',
    description: 'How long the service takes',
    required: false,
    visible: true,
    min: 0.5,
    step: 0.5,
  },
  availability: {
    id: 'availability',
    type: 'select',
    label: 'Availability',
    description: 'When this service is available',
    required: false,
    visible: true,
    options: [
      { value: 'weekdays', label: 'Weekdays Only' },
      { value: 'weekends', label: 'Weekends Only' },
      { value: 'anytime', label: 'Any Time' },
      { value: 'custom', label: 'Custom Schedule' },
    ],
  },
  location: {
    id: 'location',
    type: 'select',
    label: 'Location Type',
    description: 'Where the service is provided',
    required: false,
    visible: true,
    options: [
      { value: 'remote', label: 'Remote/Virtual' },
      { value: 'onsite', label: 'On-site' },
      { value: 'both', label: 'Both' },
    ],
  },

  // Subscription Fields
  billing_cycle: {
    id: 'billing_cycle',
    type: 'select',
    label: 'Billing Cycle',
    description: 'How often customers are billed',
    required: true,
    visible: true,
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'monthly', label: 'Monthly' },
      { value: 'yearly', label: 'Yearly' },
    ],
  },
  trial_period: {
    id: 'trial_period',
    type: 'number',
    label: 'Trial Period (Days)',
    description: 'Free trial period before billing starts',
    required: false,
    visible: true,
    min: 0,
  },
  signup_fee: {
    id: 'signup_fee',
    type: 'number',
    label: 'Signup Fee',
    description: 'One-time fee charged at signup',
    required: false,
    visible: true,
    min: 0,
    step: 0.01,
  },

  // Rental Fields
  deposit: {
    id: 'deposit',
    type: 'number',
    label: 'Deposit Amount',
    description: 'Security deposit required',
    required: false,
    visible: true,
    min: 0,
    step: 0.01,
  },
  availability_dates: {
    id: 'availability_dates',
    type: 'date',
    label: 'Available Dates',
    description: 'Date range when item is available',
    required: false,
    visible: true,
  },
  min_rental_days: {
    id: 'min_rental_days',
    type: 'number',
    label: 'Minimum Rental Days',
    description: 'Minimum number of days for rental',
    required: false,
    visible: true,
    min: 1,
  },

  // Event Fields
  event_date: {
    id: 'event_date',
    type: 'datetime',
    label: 'Event Date & Time',
    description: 'When the event takes place',
    required: true,
    visible: true,
  },
  venue: {
    id: 'venue',
    type: 'text',
    label: 'Venue',
    description: 'Location of the event',
    required: false,
    visible: true,
  },
  capacity: {
    id: 'capacity',
    type: 'number',
    label: 'Capacity',
    description: 'Maximum number of attendees',
    required: false,
    visible: true,
    min: 1,
  },

  // Bundle Fields
  bundled_products: {
    id: 'bundled_products',
    type: 'multiselect',
    label: 'Bundled Products',
    description: 'Products included in this bundle',
    required: true,
    visible: true,
  },
  bundle_price_type: {
    id: 'bundle_price_type',
    type: 'select',
    label: 'Bundle Pricing',
    description: 'How the bundle price is calculated',
    required: true,
    visible: true,
    options: [
      { value: 'fixed', label: 'Fixed Price' },
      { value: 'dynamic', label: 'Dynamic (sum of items)' },
    ],
  },
  bundle_discount: {
    id: 'bundle_discount',
    type: 'number',
    label: 'Bundle Discount (%)',
    description: 'Discount applied to bundled items',
    required: false,
    visible: true,
    min: 0,
    max: 100,
    step: 0.1,
  },
};

// Form Sections
export const FORM_SECTIONS: Record<string, FormSection> = {
  basic: {
    id: 'basic',
    title: 'Basic Information',
    description: 'Essential product details',
    icon: '📝',
    fields: ['name', 'description', 'sku'],
    is_visible: true,
  },
  pricing: {
    id: 'pricing',
    title: 'Pricing',
    description: 'Set your product pricing',
    icon: '💰',
    fields: ['price', 'cost'],
    is_visible: true,
  },
  inventory: {
    id: 'inventory',
    title: 'Inventory',
    description: 'Manage stock and availability',
    icon: '📦',
    fields: ['stock'],
    is_visible: true,
  },
  shipping: {
    id: 'shipping',
    title: 'Shipping',
    description: 'Shipping configuration',
    icon: '🚚',
    fields: ['weight', 'dimensions', 'shipping_class'],
    is_visible: true,
  },
  digital: {
    id: 'digital',
    title: 'Digital Delivery',
    description: 'Configure digital product delivery',
    icon: '💻',
    fields: ['download_limit', 'download_expiry', 'files'],
    is_visible: true,
  },
  service: {
    id: 'service',
    title: 'Service Details',
    description: 'Configure service offering',
    icon: '🛠️',
    fields: ['hourly_rate', 'duration', 'availability', 'location'],
    is_visible: true,
  },
  subscription: {
    id: 'subscription',
    title: 'Subscription Settings',
    description: 'Configure recurring billing',
    icon: '🔄',
    fields: ['recurring_price', 'billing_cycle', 'trial_period', 'signup_fee'],
    is_visible: true,
  },
  rental: {
    id: 'rental',
    title: 'Rental Settings',
    description: 'Configure rental terms',
    icon: '🚗',
    fields: ['daily_rate', 'deposit', 'availability_dates', 'min_rental_days'],
    is_visible: true,
  },
  event: {
    id: 'event',
    title: 'Event Details',
    description: 'Configure event information',
    icon: '🎫',
    fields: ['event_date', 'venue', 'capacity', 'ticket_price'],
    is_visible: true,
  },
  bundle: {
    id: 'bundle',
    title: 'Bundle Configuration',
    description: 'Configure bundled products',
    icon: '📦',
    fields: ['bundled_products', 'bundle_price_type', 'bundle_discount'],
    is_visible: true,
  },
};

// Step Configuration for Multi-step Form
export const FORM_STEPS = [
  {
    id: 'classification',
    title: 'Classification & Category',
    description: 'Choose product type and category',
    icon: '🏷️',
    required: true,
  },
  {
    id: 'basic',
    title: 'Basic Information',
    description: 'Essential product details',
    icon: '📝',
    required: true,
  },
  {
    id: 'pricing',
    title: 'Pricing & Inventory',
    description: 'Set pricing and manage stock',
    icon: '💰',
    required: true,
  },
  {
    id: 'attributes',
    title: 'Attributes & Variants',
    description: 'Configure product variations',
    icon: '🎨',
    required: false,
  },
  {
    id: 'media',
    title: 'Media & Content',
    description: 'Add images, videos, and files',
    icon: '📸',
    required: false,
  },
  {
    id: 'seo',
    title: 'SEO & Metadata',
    description: 'Optimize for search engines',
    icon: '🔍',
    required: false,
  },
  {
    id: 'review',
    title: 'Review & Save',
    description: 'Review and publish your product',
    icon: '✅',
    required: true,
  },
];
